name: "My Action"

description: "My first action"

runs:
  using: "composite"

  steps:
    - name: Hola Mundo 
      run: echo "Hola Mundo"

    - name: touch file
      run: touch hola.txt
    
    - name: Set text
      run: echo "Hola Mundo" > hola.txt

    - name: Read file 
      run: cat hola.txt