name: "My Action"

description: "My first action"

inputs:
  message: 
    description: "The message to print"
    required: true
    default: "Hello World"

runs:
  using: "composite"

  steps:
    - name: Hola Mundo 
      run: echo "${{ inputs.message }}"
      shell: bash

    - name: touch file
      run: touch hola.txt
      shell: bash
    
    - name: Set text
      run: echo "${{ inputs.message }}" > hola.txt
      shell: bash

    - name: Read file 
      run: cat hola.txt
      shell: bash