name: Hola Mundo

on: [push]


jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Hola Mundo 
      run: echo "Hola Mundo"

    - name: touch file
      run: touch hola.txt
    
    - name: Set text
      run: echo "Hola Mundo" > hola.txt

    - name: Read file 
      run: cat hola.txt  

  other:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: exapmle
        ports:
          - 3306:3306
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: ls
      run: |
        chmod +x script.sh
        ./script.sh

  node:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: ls
      run: ls -al 
    
    - name: Set up Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '16'
    
    - name: PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, zip, pcntl, exif, gd, pdo, mysql, sqlite, pgsql, bcmath, soap, xsl, xmlrpc, ldap, imap, tidy, gmp, opcache, apcu, memcached, redis, imagick, zmq, solr, amqp, ssh2, mongodb, igbinary, msgpack, yaml, xdebug, swoole, grpc, protobuf, event, rdkafka, inotify, smbclient, smbclient, sockets, sodium, yaml, xdebug, swoole, grpc, protobuf, event, rdkafka, inotify, smbclient, smbclient, sockets, sodium
        coverage: xdebug
        ini-values: post_max_size=256M, short_open_tag=On
        pecl: true
        composer: true
        composer-token: ${{ secrets.COMPOSER_TOKEN }}

    - name: node versions
      run: node -v

    - name: php versions
      run: php --version

    - name: ls2
      uses: ./.github/workflows/actions/my-action
      with:
        message: "Fernando"


